name: deploy branch

on:
  # manual trigger
  workflow_dispatch:
    inputs:
      branch:
        description: git branch to deploy
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch}}
      - name: Deploy
        run: echo Hello
